version: '2'

services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile
    image: dalton:latest
    container_name: dalton_controller
    ports:
      - "80:80"
    
    volumes:
      - ./app:/opt/dalton/app
      - ./run.py:/opt/dalton/run.py
      - ./rulesets:/opt/dalton/rulesets
      - ./engine-configs:/opt/dalton/engine-configs

    restart: always

  redis:
    image: redis:3.2.10
    container_name: dalton_redis  
    restart: always

###########################
##### Suricata Agents #####
###########################

# Suricata current (latest) from source
  agent-suricata-current:
    build:
      context: ./dalton-agent
      dockerfile: Dockerfiles/Dockerfile_suricata
      args:
        - SURI_VERSION=current
    image: suricata-current:latest
    container_name: suricata-current
    restart: always

# Suricata 4.0.0 from source
#  agent-suricata-4.0.0:
#    build:
#      context: ./dalton-agent
#      dockerfile: Dockerfiles/Dockerfile_suricata
#      args:
#        - SURI_VERSION=4.0.0
#    image: suricata-4.0.0:latest
#    container_name: suricata-4.0.0
#    restart: always

# Suricata 3.1.4 from source
#  agent-suricata-3.1.4:
#    build:
#      context: ./dalton-agent
#      dockerfile: Dockerfiles/Dockerfile_suricata
#      args:
#        - SURI_VERSION=3.1.4
#    image: suricata-3.1.4:latest
#    container_name: suricata-3.1.4
#    restart: always

# Suricata 3.2.3 from source
#  agent-suricata-3.2.3:
#    build:
#      context: ./dalton-agent
#      dockerfile: Dockerfiles/Dockerfile_suricata
#      args:
#        - SURI_VERSION=3.2.3
#    image: suricata-3.2.3:latest
#    container_name: suricata-3.2.3
#    restart: always

# Suricata 2.0.9 from source
  agent-suricata-2.0.9:
    build:
      context: ./dalton-agent
      dockerfile: Dockerfiles/Dockerfile_suricata
      args:
        - SURI_VERSION=2.0.9
    image: suricata-2.0.9:latest
    container_name: suricata-2.0.9
    restart: always

# Suricata 2.0.6 from source
#  agent-suricata-2.0.6:
#    build:
#      context: ./dalton-agent
#      dockerfile: Dockerfiles/Dockerfile_suricata
#      args:
#        - SURI_VERSION=2.0.6
#    image: suricata-2.06:latest
#    container_name: suricata-2.0.6
#    restart: always

# Suricata 1.3.6 from source
  agent-suricata-1.3.6:
    build:
      context: ./dalton-agent
      dockerfile: Dockerfiles/Dockerfile_suricata
      args:
        - SURI_VERSION=1.3.6
    image: suricata-1.3.6:latest
    container_name: suricata-1.3.6
    restart: always


###########################
###### Snort Agents #######
###########################

# Snort 2.9.7.0 from Ubuntu Repos
  agent-snort:
    build:
      context: ./dalton-agent
      dockerfile: Dockerfiles/Dockerfile_snort-2.9.7.0
    image: snort-2.9.7.0-repo:latest
    container_name: snort-2.9.7.0-repo
    restart: always

    # for debugging; can remove for prod
    volumes:
      - ./dalton-agent:/opt/dalton-agent

# Snort 2.9.9.0 from source
  agent-snort-2.9.9.0:
    build:
      context: ./dalton-agent
      dockerfile: Dockerfiles/Dockerfile_snort
      args:
        - SNORT_VERSION=2.9.9.0
        - DAQ_VERSION=2.0.6
    image: snort-2.9.9.0:latest
    container_name: snort-2.9.9.0
    restart: always

    # for debugging; can remove for prod
    volumes:
      - ./dalton-agent:/opt/dalton-agent


volumes:
  flask:
  suri:
