version: '2'

services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile
    image: dalton:latest
    container_name: dalton_controller
    ports:
      - "80:80"
    
    volumes:
      - ./app:/opt/dalton/app
      - ./run.py:/opt/dalton/run.py
      - ./rulesets:/opt/dalton/rulesets
      - ./engine-configs:/opt/dalton/engine-configs

    restart: always

  redis:
    image: redis:3.2.10
    container_name: dalton_redis  
    restart: always

###########################
##### Suricata Agents #####
###########################

# Suricata 3.0.0 from Ubuntu Repos; profiling not enabled
  agent-suricata:
    build:
      context: ./dalton-agent
      dockerfile: Dockerfiles/Dockerfile_suricata-3.0
    image: agent-suricata:3.0-stock
    container_name: suricata-3.0-stock
    restart: always

# Suricata 4.0.0 from source
  agent-suricata-4.0.0:
    build:
      context: ./dalton-agent
      dockerfile: Dockerfiles/Dockerfile_suricata-4.0.0
    image: agent-suricata:4.0.0
    container_name: suricata-4.0.0
    restart: always

# Suricata 2.0.6 from source
  agent-suricata-2.0.6:
    build:
      context: ./dalton-agent
      dockerfile: Dockerfiles/Dockerfile_suricata-2.0.6
    image: agent-suricata:2.0.6
    container_name: suricata-2.0.6
    restart: always

# Suricata 1.3.6 from source
  agent-suricata-1.3.6:
    build:
      context: ./dalton-agent
      dockerfile: Dockerfiles/Dockerfile_suricata-1.3.6
    image: agent-suricata:1.3.6
    container_name: suricata-1.3.6
    restart: always

###########################
###### Snort Agents #######
###########################


# Snort 2.9.7.0 from Ubuntu Repos
  agent-snort:
    build:
      context: ./dalton-agent
      dockerfile: Dockerfiles/Dockerfile_snort-2.9.7.0
    image: agent-snort:2.9.7.0-stock
    container_name: snort-2.9.7.0-stock
    restart: always

    # for debugging; can remove for prod
    volumes:
      - ./dalton-agent:/opt/dalton-agent


volumes:
  flask:
  suri:
